networks:
  custom:
    ipam:
      config:
        - subnet: 10.5.0.0/16

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
    networks:
      custom:
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - 27017:27017
    volumes:
      - /var/lib/mongodb/data
    networks:
      custom:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      custom:
  identity-svc:
    image: parsaimi/identity-svc:latest
    build: 
      context: .
      dockerfile: src/IdentityService/Dockerfile
    # image: mcr.microsoft.com/dotnet/sdk:8.0
    # container_name: identity-svc-v10
    #working_dir: /app/src
    environment:  
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=postgrespw;Database=identity
    ports:
      - 5001:80
    depends_on:
      - postgres
    command: dotnet run
    networks:
      custom:
        ipv4_address: 10.5.0.200

  gateway-svc:
    image: parsaimi/gateway-svc:latest
    build: 
      context: .
      dockerfile: src/GatewayService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
    ports:
      - 6001:80
    networks:
      custom:

  search-svc:
    image: parsaimi/search-svc:latest
    build: 
      context: .
      dockerfile: src/SearchService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq_Host=rabbitmq
      - ConnectionStrings_MongoDbConnection=mongodb://root:mongopw@mongodb
      - TypistApiServiceUrl=http://typistapi-svc
    ports:
      - 7002:80
    depends_on:
      - mongodb
      - rabbitmq
    networks:
      custom:

  typistapi-svc:
    image: parsaimi/typistapi-svc:latest
    build: 
      context: .
      dockerfile: src/TypistApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq_Host=rabbitmq
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=postgrespw;Database=users
    ports:
      - 4001:80
    depends_on:
      - postgres
      - rabbitmq
    networks:
      custom:

  web-app:
    image: parsaimi/web-app:latest
    build:
      context: .
      dockerfile: web-app/Dockerfile
    volumes:
      - /var/lib/webnext/data
    ports:
      - 3000:3000
    environment:
      - NEXTAUTH_SECRET=cantimaginewahtisthis
      - NEXTAUTH_URL=http://171.22.26.169:3000
      - NEXTAUTH_URL_INTERNAL=http://web-app
      - IDENTITY_URL=http://171.22.26.169:5001
      - IDENTITY_URL_INTERNAL=http://identity-svc
      - NEXT_PUBLIC_WEBSOCKET_URL=ws://171.22.26.169:5227
      - NEXT_PUBLIC_WEBSOCKET_URL_INTERNAL=ws://websocket-svc
      - CLIENT_SECRET=secret
      - AUTH_TRUST_HOST=true
    networks:
      custom:
  websocket-svc:
    image: parsaimi/websocket-svc:latest
    build:
      context: .
      dockerfile: chatapp-webserver/WebSocketServer/Dockerfile
    ports:
      - 5227:5227
    environment:
      - ASPNETCORE_URLS=http://+:5227
      - ASPNETCORE_ENVIRONMENT=Development

    networks:
      custom:
