version: '2'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    environment:
      - DEFAULT_EMAIL=parsaemani17@gmail.com
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
  identity-svc:
    image: parsaimi/identity-svc:latest
    build: 
      context: .
      dockerfile: src/IdentityService/Dockerfile
    # image: mcr.microsoft.com/dotnet/sdk:8.0
    # container_name: identity-svc-v10
    #working_dir: /app/src
    environment:  
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=postgrespw;Database=identity
      - ClientApp=https://app.parsaimi.xyz
      - VIRTUAL_HOST=id.parsaimi.xyz
      - LETSENCRYPT_HOST=id.parsaimi.xyz
    ports:
      - 5001:80
    depends_on:
      - postgres

  web-app:
    image: parsaimi/web-app:latest
    build:
      context: .
      dockerfile: web-app/Dockerfile
    volumes:
      - /var/lib/webnext/data
    ports:
      - 3000:3000
    environment:
      - NEXTAUTH_SECRET=cantimaginewahtisthis
      - NEXTAUTH_URL=https://app.parsaimi.xyz
      - IDENTITY_URL=https://id.parsaimi.xyz
      - IDENTITY_URL_INTERNAL=http://identity-svc
      - NEXT_PUBLIC_WEBSOCKET_URL=ws://api.parsaimi.xyz
      - NEXT_PUBLIC_WEBSOCKET_URL_INTERNAL=https://websocket-svc
      - CLIENT_SECRET=secret
      - AUTH_TRUST_HOST=true
      - VIRTUAL_HOST=app.parsaimi.xyz
      - LETSENCRYPT_HOST=app.parsaimi.xyz
  websocket-svc:
    image: parsaimi/websocket-svc:latest
    build:
      context: .
      dockerfile: chatapp-webserver/WebSocketServer/Dockerfile
    ports:
      - 5227:5227
    environment:
      - ASPNETCORE_URLS=http://+:5227
      - ASPNETCORE_ENVIRONMENT=Docker
      - VIRTUAL_HOST=api.parsaimi.xyz
      - LETSENCRYPT_HOST=api.parsaimi.xyz

volumes:
  pgdata:
  conf:
  vhost:
  html:
  certs:
  acme: