services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - 27017:27017
    volumes:
      - /var/lib/mongodb/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
  identity-svc:
    build: 
      context: .
      dockerfile: src/IdentityService/Dockerfile
    # image: mcr.microsoft.com/dotnet/sdk:8.0
    # container_name: identity-svc-v10
    #working_dir: /app/src
    environment:  
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=postgrespw;Database=identity
    ports:
      - 5001:80
    depends_on:
      - postgres
    command: dotnet run

  gateway-svc:
    build: 
      context: .
      dockerfile: src/GatewayService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
    ports:
      - 6001:80

  search-svc:
    build: 
      context: .
      dockerfile: src/SearchService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq_Host=rabbitmq
      - ConnectionStrings_MongoDbConnection=mongodb://root:mongopw@mongodb
      - TypistApiServiceUrl=http://typistapi-svc
    ports:
      - 7002:80
    depends_on:
      - mongodb
      - rabbitmq

  typistapi-svc:
    build: 
      context: .
      dockerfile: src/TypistApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq_Host=rabbitmq
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=postgrespw;Database=users
    ports:
      - 4001:80
    depends_on:
      - postgres
      - rabbitmq